server:
  port: 8086
  
  
spring:
  application:
    name: service-three
    
    
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
  jackson.serializationindent_output: true
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    
    
management:
  context-path: /devoxx
  health:
    consul:
      enabled: false
  security:
    enabled: false
    
    
  rabbitmq:
    host: rabbit
    port: 5672
    username: mudigal
    password: mudigal
    virtualHost: /

---
spring:
  profiles: default
  h2.console:
    enabled: true
    path: /h2
  datasource:
    url: jdbc:h2:mem:service-three-db
    username: sa
    password: null
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update